export const HOME_GET_DATA_BEGIN = 'HOME_GET_DATA_BEGIN';
export const HOME_GET_DATA_SUCCESS = 'HOME_GET_DATA_SUCCESS';
export const HOME_GET_DATA_FAILURE = 'HOME_GET_DATA_FAILURE';
export const HOME_GET_DATA_DISMISS_ERROR = 'HOME_GET_DATA_DISMISS_ERROR';
// AUTO MAINTAINED FILE: DO NOT CHANGE

