export const THE_DATA_PICK_UP_GET_DATA_BEGIN = 'THE_DATA_PICK_UP_GET_DATA_BEGIN';
export const THE_DATA_PICK_UP_GET_DATA_SUCCESS = 'THE_DATA_PICK_UP_GET_DATA_SUCCESS';
export const THE_DATA_PICK_UP_GET_DATA_FAILURE = 'THE_DATA_PICK_UP_GET_DATA_FAILURE';
export const THE_DATA_PICK_UP_GET_DATA_DISMISS_ERROR = 'THE_DATA_PICK_UP_GET_DATA_DISMISS_ERROR';
