export const INTERVIEW_START_INTERVIEW = 'INTERVIEW_START_INTERVIEW';
export const INTERVIEW_NEXT_PAGE = 'INTERVIEW_NEXT_PAGE';
export const INTERVIEW_PREV_PAGE = 'INTERVIEW_PREV_PAGE';
export const INTERVIEW_FINISH_INTERVIEW = 'INTERVIEW_FINISH_INTERVIEW';
