// Initial state is the place you define all initial values for the Redux store of the feature.
// In the 'standard' way, initialState is defined in reducers: http://redux.js.org/docs/basics/Reducers.html
// But when application grows, there will be multiple reducers files, it's not intuitive what data is managed by the whole store.
// So Rekit extracts the initial state definition into a separate module so that you can have
// a quick view about what data is used for the feature, at any time.

// NOTE: initialState constant is necessary so that Rekit could auto add initial state when creating async actions.

import React from 'react';
import {
  StartPage,
  FirstPage,
  SecondPage,
  ThirdListenerPage,
  FourthListenerPage,
  FifthListenerPage,
  SixthListenerPage,
  SeventhMusicianPage,
  EighthMusicianPage,
  NinethMusicianPage,
  TenthMusicianPage,
  EleventhMusicianPage,
  TwelfthMusicianPage,
  ThirteenthMusicianPage,
  FourteenthMusicianPage,
  FifteenthMusicianPage,
  SixteenthMusicianPage,
  SeventeenthMusicianPage,
  EighteenthMusicianPage,
  NineteenthMusicianPage,
  TwentiethMusicianPage,
  TwentyFirstMusicianPage,
  FinishPage,
} from './../';

const initialState = {
  interviewStages: [
    React.createElement(StartPage),
    React.createElement(FirstPage),
    React.createElement(SecondPage),
    React.createElement(ThirdListenerPage),
    React.createElement(FourthListenerPage),
    React.createElement(FifthListenerPage),
    React.createElement(SixthListenerPage),
    React.createElement(SeventhMusicianPage),
    React.createElement(EighthMusicianPage),
    React.createElement(NinethMusicianPage),
    React.createElement(TenthMusicianPage),
    React.createElement(EleventhMusicianPage),
    React.createElement(TwelfthMusicianPage),
    React.createElement(ThirteenthMusicianPage),
    React.createElement(FourteenthMusicianPage),
    React.createElement(FifteenthMusicianPage),
    React.createElement(SixteenthMusicianPage),
    React.createElement(SeventeenthMusicianPage),
    React.createElement(EighteenthMusicianPage),
    React.createElement(NineteenthMusicianPage),
    React.createElement(TwentiethMusicianPage),
    React.createElement(TwentyFirstMusicianPage),
    React.createElement(FinishPage),
  ],
  currentIndex: 0,
  pageContent: React.createElement(StartPage),
  firstFields: { city: '', age: '', gender: '', edu: '', eduOther: '', job: '' },
  secondFields: { everPlayed: '' },
  thirdFields: { interest: 3, who: '', money: '' },
  fourthFields: { songs: '' },
  fifthFields: { sign: '', traditions: '' },
  sixthFields: { experience: '' },
  seventhFields: { hobbie: '', hobbieOther: '', rather: '', ratherExact: '' },
  eighthFields: { why: '' },
  ninethFields: { community: '' },
  tenthFields: { official: '', wocom: '', howjoin: '', cookies: '' },
  eleventhFields: { meetings: '' },
  twelfthFields: { reasons: '', where: '', whywhere: '', meetingtime: ['', '', '', '', ''] },
  thirteenthFields: { place: '', descplace: '', time: '' },
  fourteenthFields: { whatplay: '', whythisplay: '', placeplay: '' },
  fifteenthFields: { howcome: '', howleave: '', firstmoney: '', talk: '' },
  sixteenthFields: { jargon: '', specsigns: '', idmarks: '', forwhat: ['', '', ''] },
  seventeenthFields: { celebrations: '', howceleb: '' },
  eighteenthFields: { competition: '', relations: '', whobest: '' },
  nineteenthFields: { events: '', reactions: '', story: '' },
  twentiethFields: { identity: '' },
  twentyFirstFields: { thanks: '', help: '' },
  checkPoints: [
    {},
    { city: '', age: '', gender: '', edu: '', eduOther: '', job: '' },
    { everPlayed: '' },
    { interest: '', who: '', money: '' },
    { songs: '' },
    { sign: '', traditions: '' },
    { experience: '' },
    { hobbie: '', rather: '' },
    { why: '' },
    { community: '' },
    { official: '', wocom: '', howjoin: '', cookies: '' },
    { meetings: '' },
    { reasons: '', where: '', whywhere: '', meetingtime: ['', '', '', '', ''] },
    { place: '', descplace: '', time: '' },
    { whatplay: '', whythisplay: '', placeplay: '' },
    { howcome: '', howleave: '', firstmoney: '', talk: '' },
    { jargon: '', specsigns: '', idmarks: '', forwhat: ['', '', ''] },
    { celebrations: '', howceleb: '' },
    { competition: '', relations: '', whobest: '' },
    { events: '', reactions: '', story: '' },
    { identity: '' },
    { thanks: '', help: '' },
  ],
  keyValues: [
    { yep: 1, nope: -1, back: -1 },
    { yep: 2, nope: -1, back: 0 },
    { yep: 7, nope: 3, back: 1 },
    { yep: 4, nope: -1, back: 2 },
    { yep: 5, nope: -1, back: 3 },
    { yep: 6, nope: -1, back: 4 },
    { yep: 21, nope: -1, back: 5 },
    { yep: 9, nope: 8, back: 2 },
    { yep: 9, nope: -1, back: 7 },
    { yep: 10, nope: 11, back: 7 },
    { yep: 11, nope: -1, back: 9 },
    { yep: 12, nope: 13, back: 10 },
    { yep: 13, nope: -1, back: 11 },
    { yep: 14, nope: -1, back: 11 },
    { yep: 15, nope: -1, back: 13 },
    { yep: 16, nope: -1, back: 14 },
    { yep: 17, nope: -1, back: 15 },
    { yep: 18, nope: -1, back: 16 },
    { yep: 19, nope: -1, back: 17 },
    { yep: 20, nope: -1, back: 18 },
    { yep: 21, nope: -1, back: 19 },
    { yep: 21, nope: -1, back: 20 },
    { yep: 22, nope: 22, back: 22 },
  ],
  currentKeyValue: '',
  lastPage: 21,
  backDoor: true,
};

export default initialState;
