export const ABOUT_US_SEND_FEEDBACK_BEGIN = 'ABOUT_US_SEND_FEEDBACK_BEGIN';
export const ABOUT_US_SEND_FEEDBACK_SUCCESS = 'ABOUT_US_SEND_FEEDBACK_SUCCESS';
export const ABOUT_US_SEND_FEEDBACK_FAILURE = 'ABOUT_US_SEND_FEEDBACK_FAILURE';
export const ABOUT_US_SEND_FEEDBACK_DISMISS_ERROR = 'ABOUT_US_SEND_FEEDBACK_DISMISS_ERROR';
